### ISSUE TITLE
Bass v17 wont build (including solution)

### ISSUE THREAD

**Issue by thar0x29a** [bass-assembler/bass-history-kit#2]
... since there are the folders "obj" and "out" missed. 
Without them beeing present and writeable gnu make will just give you some 'clues', but wont compile. 

I bet it just got removed by git because it lacks any content.

**Comment by Screwtapello** [comment]
Thanks for pointing that out.

For future reference, here's the archive-extraction code in bass-history-kit:

https://github.com/bass-assembler/bass-history-kit/blob/0a36b805a9cbf378015b2233d659f7f6344b71c8/history-fast-export#L61-L71

...and here's the equivalent archive-extraction code in ares-history-kit:

https://github.com/higan-emu/ares-history-kit/blob/b26c7c038ac1b30cd36f596bb84c9a3c92cd61eb/ares-fast-export#L52-L84

https://github.com/higan-emu/ares-history-kit/blob/b26c7c038ac1b30cd36f596bb84c9a3c92cd61eb/ares-fast-export#L123-L133

It shouldn't be too difficult to backport the code from ares-history-kit to bass-history-kit, I'll try to get around to it soon.

**Comment by Screwtapello** [comment]
I've updated the bass-history-kit repo, rebuilt bass-history, and force-pushed it. Please let me know if you find any other issues!
